[2023-10-02T02:40:01.524+0300] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_hgb.task_save_results scheduled__2023-09-30T01:00:00+00:00 [queued]>
[2023-10-02T02:40:01.529+0300] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_hgb.task_save_results scheduled__2023-09-30T01:00:00+00:00 [queued]>
[2023-10-02T02:40:01.529+0300] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-02T02:40:01.609+0300] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): task_save_results> on 2023-09-30 01:00:00+00:00
[2023-10-02T02:40:01.612+0300] {standard_task_runner.py:57} INFO - Started process 5557 to run task
[2023-10-02T02:40:01.618+0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'train_hgb', 'task_save_results', 'scheduled__2023-09-30T01:00:00+00:00', '--job-id', '66', '--raw', '--subdir', 'DAGS_FOLDER/test_dag_several_models.py', '--cfg-path', '/tmp/tmp_0ebw210']
[2023-10-02T02:40:01.620+0300] {standard_task_runner.py:85} INFO - Job 66: Subtask task_save_results
[2023-10-02T02:40:01.677+0300] {task_command.py:415} INFO - Running <TaskInstance: train_hgb.task_save_results scheduled__2023-09-30T01:00:00+00:00 [running]> on host dsbulgako1-QEMU-Virtual-Machine
[2023-10-02T02:40:01.756+0300] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='dmitrii.bulghakov@gmail.com' AIRFLOW_CTX_DAG_OWNER='Dmitry Bulgakov' AIRFLOW_CTX_DAG_ID='train_hgb' AIRFLOW_CTX_TASK_ID='task_save_results' AIRFLOW_CTX_EXECUTION_DATE='2023-09-30T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-09-30T01:00:00+00:00'
[2023-10-02T02:40:01.773+0300] {test_dag_several_models.py:151} INFO - Success.
[2023-10-02T02:40:01.784+0300] {base.py:73} INFO - Using connection ID 's3_connector' for task execution.
[2023-10-02T02:40:01.785+0300] {connection_wrapper.py:340} INFO - AWS Connection (conn_id='s3_connector', conn_type='aws') credentials retrieved from login and password.
[2023-10-02T02:40:01.828+0300] {configprovider.py:949} INFO - Found endpoint for s3 via: config_global.
[2023-10-02T02:40:02.008+0300] {python.py:194} INFO - Done. Returned value was: None
[2023-10-02T02:40:02.020+0300] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=train_hgb, task_id=task_save_results, execution_date=20230930T010000, start_date=20231001T234001, end_date=20231001T234002
[2023-10-02T02:40:02.068+0300] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-10-02T02:40:02.083+0300] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
